### ISSUE TITLE
Feature request: enable/disable content logging

### ISSUE THREAD

**Issue by dylanglockler** [Biegalski-LLC/Laravel-Mailgun-Webhooks#10]
Great package! The content logging can be a bit overkill on some projects though - it would be super useful if you had a config option to enable/disable content logging so it simply logged the events. If you're sending a lot of transactional emails, the database gets large very quickly!

In any case, thanks for sharing this great tool.

**Comment by Biegalski-LLC** [comment]
Content logging can definitely grow the database exponentially - just pushed a new release that allows you to disable logging of content, flags, tags and/or variables.

DotEnv Config Additions:
`
MAILGUN_WEBHOOKS_OPTIONS_DISABLE_CONTENT=false
MAILGUN_WEBHOOKS_OPTIONS_DISABLE_FLAG=false
MAILGUN_WEBHOOKS_OPTIONS_DISABLE_TAG=false
MAILGUN_WEBHOOKS_OPTIONS_DISABLE_VARIABLE=false
`

**Comment by dylanglockler** [comment]
Incredible! Thanks for the improvement. Really makes the package more flexible.
