### ISSUE TITLE
Сhange user table relationship

### ISSUE THREAD

**Issue by abordage** [Biegalski-LLC/Laravel-Mailgun-Webhooks#11]
Why HasOne? 
User HasMany MailgunEvent, MailgunEvent BelongsTo User

https://github.com/Biegalski-LLC/Laravel-Mailgun-Webhooks/blob/fcb3920320f825749e104dd5d867525ff25ecd35/src/Model/MailgunEvent.php#L49-L52

**Comment by Biegalski-LLC** [comment]
Must have added that before my morning coffee lol 😅

Just pushed a fix - thanks for the thorough reviewing.

**Comment by Biegalski-LLC** [comment]
Must have added that before my morning coffee lol 😅

Thank you for the thorough reviewing, just pushed a fix. v0.0.96

**Comment by abordage** [comment]
And further:
Change `config('mailgun-webhooks.users_table.*')` to `user_table`

https://github.com/Biegalski-LLC/Laravel-Mailgun-Webhooks/blob/e74745dfe8cc29f96e4c6cdb8259e7b1945d300b/src/Model/MailgunEvent.php#L54
