### ISSUE TITLE
Can't add mailgun_events_user_id_foreign foreign key during migration

### ISSUE THREAD

**Issue by unclejessiespano** [Biegalski-LLC/Laravel-Mailgun-Webhooks#13]
I'm getting the following error when I try to run the database migration:

`SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `mailgun_events` add constraint `mailgun_events_user_id_foreign` foreign key (`user_id`) references `leads` (`id`) on delete cascade)`

I'm trying to track emails I've sent to leads.  I've updated my .env file to look for leads.id in my leads table. I've changed the model from App\User to App\Models\Lead.

Any thoughts?

**Comment by Biegalski-LLC** [comment]
Apologies for the delay, your dotenv has this:

`
MAILGUN_WEBHOOKS_USER_TABLE_NAME=leads
MAILGUN_WEBHOOKS_USER_TABLE_EMAIL=email
MAILGUN_WEBHOOKS_USER_TABLE_KEY=id
MAILGUN_WEBHOOKS_USER_TABLE_FPQN=App\Models\Lead
`

Is your config cached? `php artisan config:cache`
