### ISSUE TITLE
Disable email notifications?

### ISSUE THREAD

**Issue by stufarquhar** [Biegalski-LLC/Laravel-Mailgun-Webhooks#14]
Hi there,

Just wondering how you can disable the email notifications when an event is triggered? I do not want a notification via email, just record events in the DB.

**Comment by Biegalski-LLC** [comment]
You can do this in your dotenv configuration:

```
MAILGUN_WEBHOOKS_ALERTS_TO=
MAILGUN_WEBHOOKS_ALERTS_FROM_EMAIL=
MAILGUN_WEBHOOKS_ALERTS_FROM_NAME=

MAILGUN_WEBHOOKS_TRIGGER_DELIVERED=false
MAILGUN_WEBHOOKS_TRIGGER_OPENED=false
MAILGUN_WEBHOOKS_TRIGGER_PERM_FAILURE=true
MAILGUN_WEBHOOKS_TRIGGER_SPAM=true
MAILGUN_WEBHOOKS_TRIGGER_TEMP_FAILURE=true
MAILGUN_WEBHOOKS_TRIGGER_UNSUBSCRIBE=true
```

Make sure your config file is up-to-date (https://github.com/Biegalski-LLC/Laravel-Mailgun-Webhooks/blob/master/config/mailgun-webhooks.php) and if you're caching your config, recache after setting these variables.

**Comment by bhushanc-reconnectin** [comment]
hi @Biegalski-LLC 

Even after setting above correct, still get notifications on email.

Can you please help how this can be stopped ?


Thank you
