### ISSUE TITLE
When using Mailgun Domain Sending API keys, verification fails

### ISSUE THREAD

**Issue by PunchRockgroin** [Biegalski-LLC/Laravel-Mailgun-Webhooks#19]
Was having trouble as the in buildSignature function in  Biegalski\LaravelMailgunWebhooks\Middleware at line 42 wasn't matching up resulting in a 404 when Mailgun was sending the webhook.

This is because the my use case I am using the Domain level API key, and not using the Account level API key.

https://help.mailgun.com/hc/en-us/articles/203380100-Where-Can-I-Find-My-API-Key-and-SMTP-Credentials-

The signature generated in the Mailgun Webhook is using the "HTTP webhook signing key", which is different from the  Domain level API key key, but in the buildSignature function, it's using the config value for services.mailgun.secret. 

The easy fix is to use the Account level API key, but what would fix the issue in the use case I describe is perhaps adding a specific env/config value for the "HTTP webhook signing key", like MAILGUN_WEBHOOKS_WEBHOOK_SIGNING_KEY, and then default back to the services.mailgun.secret value. This would also fix any issues if someone accidentally rotates the "HTTP webhook signing key" in the Mailgun Admin

If you want a pull request let me know but I thought maybe I would bring this to your and anyone else who uses this package's attention.

Thanks for your work in this!

**Comment by Biegalski-LLC** [comment]
Yeah, definitely put in a pull request! I think your solution is applicable and follows the 80/20 rule (could be beneficial to 80% of users). I can see splitting up the mailgun API key at the domain level rather than account level being a common case.
