### ISSUE TITLE
No relationship defined between mailgun_events and mailgun_event_contents

### ISSUE THREAD

**Issue by dylanglockler** [Biegalski-LLC/Laravel-Mailgun-Webhooks#3]
Just curious why there are no relationships defined to link mailgun_events to mailgun_event_content?

 Defining those relationships would be super useful in this awesome package!

**Comment by Union-Rich-Tech** [comment]
Looks like it was something I missed when I originally put this package together. Storing the content wasn't part of the original plan and was added after the fact. It is a good idea though, thank you!

I just pushed an update that includes these relationships. v0.0.91 - packagist is updated as well (https://packagist.org/packages/biegalski-llc/laravel-mailgun-webhooks)

**Comment by Biegalski-LLC** [comment]
Looks like it was something I missed when I originally put this package together. Storing the content wasn't part of the original plan and was added after the fact. It is a good idea though, thank you!

I just pushed an update that includes these relationships. v0.0.91 - packagist is updated as well (https://packagist.org/packages/biegalski-llc/laravel-mailgun-webhooks)

**Comment by dylanglockler** [comment]
WOW thanks! That's brilliant! Really appreciate it!
