### ISSUE TITLE
There is a problem installing on Centos due to case sensitive

### ISSUE THREAD

**Issue by abordage** [Biegalski-LLC/Laravel-Mailgun-Webhooks#4]
Hi. Thanks for the package, great idea.

There is a problem installing on Centos due to case sensitive

`\Exception\\DirectoryNotFoundException(code: 0): The ".../vendor/biegalski-llc/laravel-mailgun-webhooks/src/Views" directory does not exist`

https://github.com/Biegalski-LLC/Laravel-Mailgun-Webhooks/blob/master/src/LaravelMailgunWebhooksServiceProvider.php#L47

**Comment by Union-Rich-Tech** [comment]
Yikes, my apologies! It installs fine for me on Ubuntu so that is strange. However, I just pushed a fix. Give it another go and let me know! Sorry about that.

**Comment by Biegalski-LLC** [comment]
Yikes, my apologies! It installs fine for me on Ubuntu so that is strange. However, I just pushed a fix. Give it another go and let me know! Sorry about that.

**Comment by abordage** [comment]
2 new problems:

1. after `artisan view:cache`:
`The ".../vendor/biegalski-llc/laravel-mailgun-webhooks/src/views" directory does not exist`

2. `Return value of Biegalski\\LaravelMailgunWebhooks\\Services\\MailgunAlertService::sendAlert() must be of the type bool or null, none returned at .../vendor/biegalski-llc/laravel-mailgun-webhooks/src/Services/MailgunAlertService.php:82)`
