### ISSUE TITLE
Unable to delete user

### ISSUE THREAD

**Issue by abordage** [Biegalski-LLC/Laravel-Mailgun-Webhooks#8]
After installing the package, unable to delete user because `FOREIGN KEY` is set to `RESTRICT`.

There are two options: `CASCADE` on all `mailgun_*` tables or `SET NULL` on `mailgun_events`

I created migrations with `CASCADE` and can do pull request

*sorry for my English

**Comment by Biegalski-LLC** [comment]
Your English is good. I agree Cascade is the best option.
